version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.12
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      PYTHONPATH: /workspaces/birds_of_vinca/libs:${PYTHONPATH}

  db:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: bov_db_user
      MONGO_INITDB_ROOT_PASSWORD: bov_db
      # You can customize these credentials as needed

volumes:
  mongodb-data:
